// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0-M8mjZngpLsquv4pL0XypawlQZqcC9M',
    appId: '1:393661307115:web:83c1a14373a532b2bd86ae',
    messagingSenderId: '393661307115',
    projectId: 'event-management-app-2ce97',
    authDomain: 'event-management-app-2ce97.firebaseapp.com',
    storageBucket: 'event-management-app-2ce97.firebasestorage.app',
    measurementId: 'G-BK0DMYCZFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpvIPV2knrPJWZL10iSKIIcXAPhXRhGys',
    appId: '1:393661307115:android:cc60136a9158ff4ebd86ae',
    messagingSenderId: '393661307115',
    projectId: 'event-management-app-2ce97',
    storageBucket: 'event-management-app-2ce97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpJ-wClyL0oT-R9dCXjPnVMf-itX0-hzI',
    appId: '1:393661307115:ios:2391358e034ace0fbd86ae',
    messagingSenderId: '393661307115',
    projectId: 'event-management-app-2ce97',
    storageBucket: 'event-management-app-2ce97.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpJ-wClyL0oT-R9dCXjPnVMf-itX0-hzI',
    appId: '1:393661307115:ios:2391358e034ace0fbd86ae',
    messagingSenderId: '393661307115',
    projectId: 'event-management-app-2ce97',
    storageBucket: 'event-management-app-2ce97.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0-M8mjZngpLsquv4pL0XypawlQZqcC9M',
    appId: '1:393661307115:web:14376e5f5fac0d93bd86ae',
    messagingSenderId: '393661307115',
    projectId: 'event-management-app-2ce97',
    authDomain: 'event-management-app-2ce97.firebaseapp.com',
    storageBucket: 'event-management-app-2ce97.firebasestorage.app',
    measurementId: 'G-K12XPQQ49L',
  );
}
